"""initial_schema

Revision ID: d2781838fb3c
Revises: 
Create Date: 2026-02-28 10:57:39.992896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2781838fb3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_signal_daily',
    sa.Column('date_key', sa.String(length=10), nullable=False),
    sa.Column('sessions_started', sa.Integer(), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('meaningful_sessions', sa.Integer(), nullable=False),
    sa.Column('avg_user_value_rating', sa.Float(), nullable=False),
    sa.Column('adaptation_helpful_rate', sa.Float(), nullable=False),
    sa.Column('day7_returning_users', sa.Integer(), nullable=False),
    sa.Column('unique_active_users', sa.Integer(), nullable=False),
    sa.Column('bhav_pass_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('ecosystem_usage_daily',
    sa.Column('date_key', sa.String(length=10), nullable=False),
    sa.Column('inbound_partner_events', sa.Integer(), nullable=False),
    sa.Column('outbound_webhooks_queued', sa.Integer(), nullable=False),
    sa.Column('exports_generated', sa.Integer(), nullable=False),
    sa.Column('wearable_adapter_events', sa.Integer(), nullable=False),
    sa.Column('content_export_events', sa.Integer(), nullable=False),
    sa.Column('unique_partner_sources', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('eval_drift_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseline_name', sa.String(length=120), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rigor_score', sa.Float(), nullable=False),
    sa.Column('total_score_delta', sa.Float(), nullable=False),
    sa.Column('rigor_score_delta', sa.Float(), nullable=False),
    sa.Column('attempt_pass_rate_mean', sa.Float(), nullable=False),
    sa.Column('attempt_pass_rate_std', sa.Float(), nullable=False),
    sa.Column('ci95_low', sa.Float(), nullable=False),
    sa.Column('ci95_high', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_drift_snapshots_status'), 'eval_drift_snapshots', ['status'], unique=False)
    op.create_table('integration_export_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('export_type', sa.String(length=120), nullable=False),
    sa.Column('adapter_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_export_logs_adapter_id'), 'integration_export_logs', ['adapter_id'], unique=False)
    op.create_index(op.f('ix_integration_export_logs_export_type'), 'integration_export_logs', ['export_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('adapter_id', sa.String(length=80), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_adapter_id'), 'webhook_subscriptions', ['adapter_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('biometric_enabled', sa.Boolean(), nullable=False),
    sa.Column('environmental_enabled', sa.Boolean(), nullable=False),
    sa.Column('raw_audio_storage_enabled', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('practice_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('total_practice_minutes', sa.Float(), nullable=False),
    sa.Column('avg_flow_score', sa.Float(), nullable=False),
    sa.Column('avg_pronunciation_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mantra_key', sa.String(length=80), nullable=True),
    sa.Column('intention', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=40), nullable=True),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_event_type'), 'webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_subscription_id'), 'webhook_deliveries', ['subscription_id'], unique=False)
    op.create_table('adaptation_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('tempo_bpm', sa.Integer(), nullable=False),
    sa.Column('guidance_intensity', sa.String(length=20), nullable=False),
    sa.Column('key_center', sa.String(length=8), nullable=False),
    sa.Column('adaptation_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptation_decisions_session_id'), 'adaptation_decisions', ['session_id'], unique=False)
    op.create_table('bhav_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('mantra_key', sa.String(length=120), nullable=True),
    sa.Column('lineage_id', sa.String(length=60), nullable=False),
    sa.Column('profile_name', sa.String(length=40), nullable=False),
    sa.Column('discipline', sa.Float(), nullable=False),
    sa.Column('resonance', sa.Float(), nullable=False),
    sa.Column('coherence', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('passes_golden', sa.Boolean(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bhav_evaluations_session_id'), 'bhav_evaluations', ['session_id'], unique=False)
    op.create_table('session_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_event_id', sa.String(length=120), nullable=True),
    sa.Column('ingestion_source', sa.String(length=40), nullable=False),
    sa.Column('source_adapter', sa.String(length=80), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_event_id', name='uq_session_client_event')
    )
    op.create_index(op.f('ix_session_events_event_time'), 'session_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_session_events_event_type'), 'session_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_session_events_session_id'), 'session_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_events_source_adapter'), 'session_events', ['source_adapter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_events_source_adapter'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_session_id'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_event_type'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_event_time'), table_name='session_events')
    op.drop_table('session_events')
    op.drop_index(op.f('ix_bhav_evaluations_session_id'), table_name='bhav_evaluations')
    op.drop_table('bhav_evaluations')
    op.drop_index(op.f('ix_adaptation_decisions_session_id'), table_name='adaptation_decisions')
    op.drop_table('adaptation_decisions')
    op.drop_index(op.f('ix_webhook_deliveries_subscription_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_type'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('practice_progress')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_webhook_subscriptions_adapter_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_table('users')
    op.drop_index(op.f('ix_integration_export_logs_export_type'), table_name='integration_export_logs')
    op.drop_index(op.f('ix_integration_export_logs_adapter_id'), table_name='integration_export_logs')
    op.drop_table('integration_export_logs')
    op.drop_index(op.f('ix_eval_drift_snapshots_status'), table_name='eval_drift_snapshots')
    op.drop_table('eval_drift_snapshots')
    op.drop_table('ecosystem_usage_daily')
    op.drop_table('business_signal_daily')
    # ### end Alembic commands ###
